settings:
  title: 'Status Page'
  url: 'https://status.kabir.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: s3-kabr-dev
    name: Scale S3 (MinIO)
    url: 'https://s3.kabr.dev'
    
  - id: dash-kube-eu-org # unique identifier
    name: Kubernetes Dashboard (Home)
    # description: 'Dashboard for Home Kubernetes Cluster' # default=empty
    url: 'https://dash.kube.eu.org' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: home-kwatra-me
    name: Home Assistant
    url: 'https://home.kwatra.me'
    linkable: true # allows the title to be a link, default=true

  - id: pm-kwatra-me
    name: Bitwarden Stable
    url: 'https://pm.kwatra.me'
    
  - id: bw-kwatra-me
    name: Bitwarden Canary
    url: 'https://bw.kwatra.me'
    
  - id: photo-kwatra-me
    name: Photoprism
    url: 'https://photos.kwatra.me'
